<?php

/**
 * @file
 * Play with Entities
 *
 * Creates entity type 'Artwork'
 */

include_once DRUPAL_ROOT . '/sites/all/modules/det/include/tools.inc';


/**
 * Implements hook_entity_info().
 *
 * Called on module install or 'page and else cache' clear.
 */
function artcol_entity_info() {
  det_trace_funct();

  $entity['artwork'] = array(
    'label' => t('Artwork'),
    // 'controller class' => 'ArtworkController',
    'base table' => 'artwork',
    'revision table' => 'artwork_revision',
    // defaults to TRUE so not needed to be specified 'static cache' => TRUE,
    'uri callback' => 'artcol_callback_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'aid',
      'revision' => 'vid',
      'bundle' => 'type',
      'label' => 'title',
    ),
    'bundle keys' => array(
      'bundle' =>
    ),
    'bundles' => array();
    'view modes' => array(
      'full' => array(
        'label' => t('Artwork Full content'),
        'custom settings' => FALSE,
      ),
      'teaser' => array(
        'label' => t('Artwork Teaser'),
        'custom settings' => FALSE,
      ),
    ),
  );


  dpm($entity);

  return $entity;
}


/**
 * Implements callback_entity_info_uri().
 */
function artcol_callback_uri($artwork) {
  det_trace_funct();
  dpm($entity);

  return array(
    'path' => 'artwork/' . $artwork.aid,
  );
}


/**
 * Define bundles of artwork entity
 */
function artcol_artwork_type() {
  det_trace_funct();
  //$types =
}
